on: [push]

name: AzurePowerShellLoginSample

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true

      - name: Run Azure PowerShell script
        run: |
          Get-AzVM -ResourceGroupName "ResourceGroup11"
